services:
  db:
    image: postgres:16-alpine
    volumes:
      - /var/postgres/moviedb:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
      - ./data:/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: movies
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    networks:
      - back_net

  web: 
    build:
      context: ./web-app
      dockerfile: Dockerfile
    env_file:
      - ./web-app/.env
    ports:
      - 8000:8000 
    networks:
      - front_net  
      - back_net   
    depends_on: 
      - db
      - redis

  redis: 
    image: redis:8-alpine
    ports:
    - 6379:6379
    networks:
      - back_net
  
  nginx: 
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    ports: 
      - 80:80
    depends_on:
      - web
    networks:
      - front_net

networks: 
  front_net:
  back_net:

   